USE FlightSupportSystem;


DROP TABLE IF EXISTS Seat;

DROP TABLE IF EXISTS ServiceClass;

DROP TABLE IF EXISTS Bonus;

DROP TABLE IF EXISTS ParticularFlight;

DROP TABLE IF EXISTS Flight;

DROP TABLE IF EXISTS Airport;

DROP TABLE IF EXISTS Airline;

DROP TABLE IF EXISTS Client;

DROP TABLE IF EXISTS Administrator;


DROP DATABASE IF EXISTS FlightSupportSystem;
